---
# tasks file for pulp_rpm_prerequisites

- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- name: Add libmodulemd repo for Ubuntu
  apt_repository:
    repo: ppa:directhex/mock-dnf
  when:
    - ansible_distribution == "Ubuntu"
  become: true

- name: Install requested RPM packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages }}'
  become: true

- name: Fail if we do not have prereq_pip_packages
  fail:
    msg:
      - 'Error: The variable prereq_pip_packages is not defined from the pulp role.'
      - 'You are probably running this role individually, or dynamically w/ include_role.'
      - 'See README.md on how to set pulp_install_plugins to run it within the "pulp" role.'
      - 'This role has completed everything else successfully. If you wish to continue,'
      - 'you will need to pip install these packages manually:'
      - '{{ rpm_prereq_pip_packages }}'
  when:
    - rpm_prereq_pip_packages is defined
    - prereq_pip_packages is not defined

- name: Merge rpm_prereq_pip_packages into prereq_pip_packages
  set_fact:
    prereq_pip_packages: "{{ prereq_pip_packages + rpm_prereq_pip_packages }}"
  when:
    - rpm_prereq_pip_packages is defined
    - prereq_pip_packages is defined

# This puts the value of "true" into the correct scope, and makes it
# higher priority than the pulp/defaults/. The alternative would be to
# modify the include_roles task in ansible-pulp.
- name: Set pulp_use_system_wide_pkgs for the pulp role
  include_vars:
    file: main.yml  # pulp_rpm_prerequisites/vars/main.yml
