---
# tasks file for pulp_rpm_prerequisites

- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- name: Add libmodulemd repo for Ubuntu
  apt_repository:
    repo: ppa:directhex/mock-dnf
  when:
    - ansible_distribution == "Ubuntu"
  become: true

- name: Add copr repo for pulp_rpm
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/mikedep333/pulp_rpm_deps/repo/epel-7/mikedep333-pulp_rpm_deps-epel-7.repo
    dest: /etc/yum.repos.d/mikedep333-pulp_rpm_deps-epel-7.repo
    mode: 0644
    owner: root
    group: root
  when:
    - ansible_distribution in ['RedHat','CentOS']
    - ansible_distribution_major_version|int == 7
  become: true

- name: Install requested RPM packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages }}'
  become: true

- name: Fail if we do not have prereq_pip_packages
  fail:
    msg:
      - 'Error: The variable prereq_pip_packages is not defined from the pulp role.'
      - 'You are probably running this role individually, or dynamically w/ include_role.'
      - 'See README.md on how to set pulp_install_plugins to run it within the "pulp" role.'
      - 'This role has completed everything else successfully. If you wish to continue,'
      - 'you will need to pip install these packages manually:'
      - '{{ rpm_prereq_pip_packages }}'
  when:
    - rpm_prereq_pip_packages is defined
    - prereq_pip_packages is not defined

- name: Merge rpm_prereq_pip_packages into prereq_pip_packages
  set_fact:
    prereq_pip_packages: "{{ prereq_pip_packages + rpm_prereq_pip_packages }}"
  when:
    - rpm_prereq_pip_packages is defined
    - prereq_pip_packages is defined
